### ISSUE TITLE
connector.getPath() is not a function

### ISSUE THREAD

**Issue by eslamoo** [nitinsurana/jsPlumb-Persistence#4]
Hello @nitinsurana,
Thanks for helping me out in the previous issue, it seems like the `getPath()` function doesn't work with version `2.13.3` of jsPlumb and i realize that your demo uses an older version so maybe we need alternative function here
![86102312-a3530880-babb-11ea-806f-641850d24983](https://user-images.githubusercontent.com/32875906/86123916-97c30a00-bada-11ea-883b-7cd509d5213c.png)
.
